const fs = require('fs');

// function saveBase64Image(base64String, filename) {
//     // Remove the "data:image/png;base64," part
//     const  base64Data = base64String.replace(/^data:image\/png;base64,/, "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAAAklEQVR4AewaftIAAAd3SURBVO3BQY4cy5LAQDLQ978yR0tfJZCoaj39GDezP1jrEoe1LnJY6yKHtS5yWOsih7UucljrIoe1LnJY6yKHtS5yWOsih7UucljrIoe1LnJY6yKHtS7yw4dU/qaKJypTxW9SmSr+JSpvVEwqf1PFJw5rXeSw1kUOa13khy+r+CaVNyomlTcqJpWpYqqYVJ5UTCpTxaQyVUwqTyomlU9UfJPKNx3WushhrYsc1rrID79M5Y2KN1SeVEwqT1TeUPlExaTyRsUTlaliUvmEyhsVv+mw1kUOa13ksNZFfrhMxaTypOKJyqQyVUwqU8UbFZPKpDJVTCr/nx3WushhrYsc1rrID5dRmSomlUllqpgqJpU3VJ5UfELlScWkcrPDWhc5rHWRw1oX+eGXVfxLKp6oTBWfqJhUJpWpYqr4l1X8Sw5rXeSw1kUOa13khy9T+S9VTCpTxaQyVUwqU8WkMlVMKlPFpPJEZaqYVKaKSWWqmFTeUPmXHda6yGGtixzWusgPH6r4X1bxiYpJ5Y2KSeWbKj5R8b/ksNZFDmtd5LDWRewPPqAyVUwq31TxCZU3Kp6oTBXfpPJNFZPKVDGpfFPFbzqsdZHDWhc5rHUR+4MPqLxR8URlqphUpoo3VL6p4onKVDGpPKn4hMqTiknljYpJ5Y2KbzqsdZHDWhc5rHWRH/4xFZPKVPFNFZPKVDGpTCpvqEwVn1CZKp5UTCpPKiaVSWWqmFSeqEwVnzisdZHDWhc5rHWRHz5U8YbKVPGk4jepTBWTypOKN1QmlU9UvKHym1SeVEwq33RY6yKHtS5yWOsiP3xI5UnFVDGp/KaKqWJSmVSmiknlicpU8aTiicobKk8q3lCZKiaVN1R+02GtixzWushhrYvYH3xAZar4m1SeVLyh8qRiUpkqnqhMFW+oTBX/EpWpYlKZKr7psNZFDmtd5LDWRX74y1SeVEwqU8VUMak8UZkqnlRMKlPFE5WpYlJ5UjFVvKHypGJSeVIxqfxLDmtd5LDWRQ5rXeSHD1VMKlPFk4onFZPKk4onFZPKVDGpTBWTylQxVbxR8QmVT1RMKm9U/JcOa13ksNZFDmtdxP7gi1T+ZRVPVKaKSWWqeKLyiYpPqLxRMan8TRWfOKx1kcNaFzmsdZEfPqTyRsWk8qTiEypPVD6hMlVMFW+ovKEyVUwV31QxqUwVT1Smim86rHWRw1oXOax1kR/+YxVPVKaKT6hMFZPKk4onKk8qJpUnKk8qJpWp4g2VqWJSmSomlTdUpopPHNa6yGGtixzWusgPH6qYVJ6oPKmYKiaVJxXfpDJVTCpTxaTypGJS+UTFpDJVfKJiUnlSMalMFd90WOsih7UucljrIj98SOWNiknlicpU8URlqphUnlT8TSpTxaTyROUTKk9U3qj4Lx3WushhrYsc1rqI/cEHVKaKSeVJxaQyVUwqn6iYVKaKJyrfVDGpTBWTylQxqTypmFSeVLyhMlX8TYe1LnJY6yKHtS7yw5epPKmYVKaKSeUTFZPKVDGpTBVTxaTypOKbKt6omFSmiicqU8WTiicqU8U3Hda6yGGtixzWuoj9wV+k8kbFE5VPVEwqTyqeqDypmFSeVEwqTyomlTcqJpWpYlKZKv5Lh7UucljrIoe1LvLDh1Smim9SeVIxqTypeFIxqUwqTyreqJhUPqEyVUwqn1B5Q+WNik8c1rrIYa2LHNa6yA9fpvKk4onKVPFGxROVJxVvVDxRmSomlTcqJpWp4knFpDKp/KaK33RY6yKHtS5yWOsi9gcfUJkqJpWp4onKk4onKp+oeKLyTRXfpDJVvKHypOITKk8qPnFY6yKHtS5yWOsiP/yyikllqpgqnqhMFd+kMlU8qXhDZVL5poo3VKaKSeWJylQxqUwVk8o3Hda6yGGtixzWusgPv0zlEypPVKaKSWWqmFR+k8obFZPKVDGpTCqfUHmi8kTlv3RY6yKHtS5yWOsi9gf/w1SmiicqU8UTlTcqnqg8qZhUpoonKlPFE5Wp4g2VqeKJypOKTxzWushhrYsc1rrIDx9S+ZsqpopJZap4ojJVPKmYVJ6oTBWTyidUfpPKVPEvO6x1kcNaFzmsdZEfvqzim1SeqEwVk8pU8URlqvhExScqnlRMKpPKVPFGxW+q+KbDWhc5rHWRw1oX+eGXqbxR8S9RmSqmiicqU8UTlScVk8obKk9UvknlbzqsdZHDWhc5rHWRHy6j8kRlqpgqJpVJ5Y2KJxWTylQxqTypeEPljYpJZVJ5UvGbDmtd5LDWRQ5rXeSHy1RMKm+oPKl4ojKpTBWTylTxRsUTlaniScUTlaniicoTlaniE4e1LnJY6yKHtS7ywy+r+E0Vk8pUMal8k8pU8UbFpDJVTBWTylTxROWJypOKJyr/pcNaFzmsdZHDWhf54ctU/iaVqeKbKj6hMlU8qZhUpoqpYlJ5UjGpPKmYVKaKqeKJym86rHWRw1oXOax1EfuDtS5xWOsih7UucljrIoe1LnJY6yKHtS5yWOsih7UucljrIoe1LnJY6yKHtS5yWOsih7UucljrIv8HyovOpHhmKy8AAAAASUVORK5CYII= ");

//     // Write the file
//     fs.writeFileSync(qrcode.txt, base64Data, 'base64');
//     console.log(`✅ Image saved as ${filename}`);
// };
// saveBase64Imag


function saveBase64Image(base64String, filename) {
    // Strip only the data URL header if present
    const base64Data = base64String.replace(/^data:image\/png;base64,/, '');

    // Save as a PNG file
    fs.writeFileSync(filename, base64Data, 'base64');
    console.log(`✅ Image saved as ${filename}`);
}

